### ISSUE TITLE
DOC003 - Organização do git pages

### ISSUE THREAD

**Issue by AdneMoretti** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#3]
Organização do github pages: 

- [x] Adicionar sobre e participantes do projeto; 
- [x] Adicionar heatmap que foi feito na plataforma when2meet; 
- [ ] Adicionar tópico de sprints e já colocar a ata da primeira reunião de kickoff do produto; 
- [ ] Adicionar tópico de Lean Inception para adição das etapas a serem desenvolvidas do lean inception;

**Comment by MorettiGS** [comment]
Primeiro check realizado. Adicionado como aba "Início" no mkdocs do projeto.
